version: "3.7"

services:
  web-tableau:
    build:
      context: .
      dockerfile: ./apps/Tableau/Dockerfile
    container_name: web-tableau
    volumes:
      - ./apps/Tableau:/monorepo/apps/Tableau
      - ./packages:/monorepo/packages
      - ./node_modules:/monorepo/node_modules
      - ./apps/Tableau/.next:/monorepo/Tableau/.next
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    ports:
      - "3000:3000"
      - "9229:9229"
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tableau
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
