import { Role } from '../../enums/role.enum'
import { PermissionPolicy } from '../../enums/permission.enum'

export const RolePolicy = {
    [Role.Owner]: [
        PermissionPolicy.ReadBoardList,
        PermissionPolicy.ReadBoard,
        PermissionPolicy.ReadTask,
        PermissionPolicy.ReadBoardUserSharing,
        PermissionPolicy.CreateBoard,
        PermissionPolicy.CreateTask,
        PermissionPolicy.CreateStatus,
        PermissionPolicy.CreateBoardUserSharing,
        PermissionPolicy.UpdateBoard,
        PermissionPolicy.UpdateTask,
        PermissionPolicy.UpdateStatus,
        PermissionPolicy.UpdateBoardUserSharing,
        PermissionPolicy.DeleteBoard,
        PermissionPolicy.DeleteTask,
        PermissionPolicy.DeleteStatus,
        PermissionPolicy.DeleteBoardUserSharing,
    ],
    [Role.Administrator]: [
        PermissionPolicy.ReadBoardList,
        PermissionPolicy.ReadBoard,
        PermissionPolicy.ReadTask,
        PermissionPolicy.ReadBoardUserSharing,
        PermissionPolicy.CreateBoard,
        PermissionPolicy.CreateTask,
        PermissionPolicy.CreateStatus,
        PermissionPolicy.CreateBoardUserSharing,
        PermissionPolicy.UpdateBoard,
        PermissionPolicy.UpdateTask,
        PermissionPolicy.UpdateStatus,
        PermissionPolicy.UpdateBoardUserSharing,
        PermissionPolicy.DeleteTask,
        PermissionPolicy.DeleteStatus,
        PermissionPolicy.DeleteBoardUserSharing,
    ],
    [Role.Collaborator]: [
        PermissionPolicy.ReadBoardList,
        PermissionPolicy.ReadBoard,
        PermissionPolicy.ReadTask,
        PermissionPolicy.ReadBoardUserSharing,
        PermissionPolicy.CreateTask,
        PermissionPolicy.UpdateTask,
        PermissionPolicy.DeleteTask,
    ],
    [Role.Guest]: [
        PermissionPolicy.ReadBoardList,
        PermissionPolicy.ReadBoard,
        PermissionPolicy.ReadTask,
        PermissionPolicy.ReadBoardUserSharing,
    ],
}
